const ADJECTIVES = [
  "agile",
  "amber",
  "bold",
  "brisk",
  "calm",
  "clever",
  "cosmic",
  "crisp",
  "daring",
  "eager",
  "fuzzy",
  "gentle",
  "golden",
  "happy",
  "humble",
  "jolly",
  "keen",
  "lively",
  "lucky",
  "mellow",
  "merry",
  "nimble",
  "noble",
  "quick",
  "quiet",
  "rapid",
  "sunny",
  "swift",
  "tidy",
  "vivid",
  "witty",
  "zesty",
];
const ANIMALS = [
  "otter",
  "badger",
  "beaver",
  "bison",
  "condor",
  "cougar",
  "crane",
  "dolphin",
  "falcon",
  "ferret",
  "finch",
  "gecko",
  "heron",
  "ibis",
  "jaguar",
  "koala",
  "lemur",
  "lynx",
  "marmot",
  "moose",
  "narwhal",
  "ocelot",
  "osprey",
  "panda",
  "pelican",
  "puffin",
  "quokka",
  "raven",
  "salmon",
  "tapir",
  "walrus",
  "wombat",
];

/** Default machine label, e.g. "brisk-otter". */
export function randomLabel(random: () => number = Math.random): string {
  const pick = (list: string[]): string =>
    list[Math.min(list.length - 1, Math.floor(random() * list.length))] ?? list[0]!;
  return `${pick(ADJECTIVES)}-${pick(ANIMALS)}`;
}
