import type { Metric, MetricKey, SummaryResult } from "@convex/lib/types";
import {
  EM_DASH,
  formatCompact,
  formatDurationMs,
  formatHours,
  formatInt,
  formatPercent,
  formatUsd,
} from "./format";

export type MetricKind = "tokens" | "usd" | "percent" | "duration" | "hours" | "count" | "ratio";
/** `"neutral"` = the direction carries no verdict (spending more is neither good nor bad). */
export type GoodDirection = "up" | "down" | "neutral";
export type MetricDef = {
  key: MetricKey;
  label: string;
  kind: MetricKind;
  goodDirection: GoodDirection;
  help: string;
};

function def(
  key: MetricKey,
  label: string,
  kind: MetricKind,
  goodDirection: GoodDirection,
  help: string,
): MetricDef {
  return { key, label, kind, goodDirection, help };
}

export const METRIC_DEFS: Record<MetricKey, MetricDef> = {
  totalTokens: def(
    "totalTokens",
    "Total tokens",
    "tokens",
    "up",
    "Input + output tokens of every model response in the period, including sub-agent threads.",
  ),
  inputTokens: def(
    "inputTokens",
    "Input context",
    "tokens",
    "up",
    "Prompt tokens sent to the model (cached tokens included).",
  ),
  cachedInputTokens: def(
    "cachedInputTokens",
    "Cached input",
    "tokens",
    "up",
    "Input tokens served from the prompt cache.",
  ),
  outputTokens: def(
    "outputTokens",
    "Output tokens",
    "tokens",
    "up",
    "Tokens generated by the model (reasoning included).",
  ),
  reasoningTokens: def(
    "reasoningTokens",
    "Reasoning tokens",
    "tokens",
    "up",
    "Hidden reasoning tokens, a subset of output tokens.",
  ),
  subagentTokens: def(
    "subagentTokens",
    "Sub-agent tokens",
    "tokens",
    "up",
    "Tokens used by sub-agent threads such as the auto-review guardian. Included in total tokens and cost, because they draw on the same shared quota.",
  ),
  subagentSessions: def(
    "subagentSessions",
    "Sub-agent threads",
    "count",
    "neutral",
    "Threads Codex spawned on its own. Excluded from the session, turn and message counts above, which reflect only the threads you drove.",
  ),
  costUsd: def(
    "costUsd",
    "Estimated cost",
    "usd",
    "neutral",
    "Tokens priced at OpenAI API list prices from the Settings page. Unpriced models count as $0.",
  ),
  linesAdded: def(
    "linesAdded",
    "Generated lines",
    "count",
    "up",
    "Lines added by file changes (diff '+' lines plus new-file contents).",
  ),
  linesRemoved: def(
    "linesRemoved",
    "Removed lines",
    "count",
    "neutral",
    "Lines removed by file changes.",
  ),
  filesChanged: def(
    "filesChanged",
    "Files changed",
    "count",
    "up",
    "Files touched by file-change items.",
  ),
  sessions: def(
    "sessions",
    "Sessions",
    "count",
    "up",
    "Codex threads started in the period (sub-agent threads excluded).",
  ),
  turns: def("turns", "Turns", "count", "up", "User turns (task_started events) in main threads."),
  responses: def("responses", "Responses", "count", "up", "Model responses (token events)."),
  messages: def("messages", "Messages", "count", "up", "User plus agent messages in main threads."),
  userMessages: def("userMessages", "User messages", "count", "up", "Messages typed by the user."),
  agentMessages: def(
    "agentMessages",
    "Agent messages",
    "count",
    "up",
    "Messages written by the agent.",
  ),
  cacheHitRate: def(
    "cacheHitRate",
    "Cache hit rate",
    "percent",
    "up",
    "Cached input tokens divided by input tokens.",
  ),
  tokensPerTurn: def(
    "tokensPerTurn",
    "Tokens per turn",
    "tokens",
    "down",
    "Total tokens divided by turns.",
  ),
  tokensPerLine: def(
    "tokensPerLine",
    "Tokens per line",
    "tokens",
    "down",
    "Total tokens divided by generated lines.",
  ),
  avgSessionActiveMs: def(
    "avgSessionActiveMs",
    "Avg session",
    "duration",
    "up",
    "Active time divided by sessions.",
  ),
  activeRate: def(
    "activeRate",
    "Active rate",
    "percent",
    "up",
    "Active time divided by wall time.",
  ),
  activeMs: def(
    "activeMs",
    "Active hours",
    "hours",
    "up",
    "Sum of turn durations (the model was working).",
  ),
  wallMs: def(
    "wallMs",
    "Total hours",
    "hours",
    "up",
    "Sum of session spans from first to last event.",
  ),
  ttftAvgMs: def(
    "ttftAvgMs",
    "TTFT mean",
    "duration",
    "down",
    "Mean time to first token per turn.",
  ),
  ttftP50Ms: def(
    "ttftP50Ms",
    "TTFT median",
    "duration",
    "down",
    "Approximate median time to first token, interpolated from a 16-bucket histogram.",
  ),
  compactions: def(
    "compactions",
    "Compactions",
    "count",
    "down",
    "Context compactions (a sign of long, expensive threads).",
  ),
  activeDays: def(
    "activeDays",
    "Active days",
    "count",
    "up",
    "Days with at least one session or token event.",
  ),
};

export const VOLUME_CARD_KEYS = ["totalTokens", "costUsd", "linesAdded", "sessions"] as const;
export const EFFICIENCY_CARD_KEYS = [
  "cacheHitRate",
  "tokensPerTurn",
  "avgSessionActiveMs",
  "ttftP50Ms",
  "compactions",
] as const;
export const USER_OVERVIEW_KEYS = [
  "costUsd",
  "totalTokens",
  "linesAdded",
  "tokensPerLine",
  "inputTokens",
  "outputTokens",
  "activeDays",
  "cacheHitRate",
  "activeMs",
  "sessions",
  "wallMs",
  "messages",
  "userMessages",
  // Last, and adjacent: they are the footnote to `sessions` and `totalTokens` above, explaining
  // why one counts sub-agent work and the other does not.
  "subagentTokens",
  "subagentSessions",
] as const;

export function formatMetricValue(kind: MetricKind, value: number | null): string {
  if (value === null || !Number.isFinite(value)) return EM_DASH;
  switch (kind) {
    case "tokens":
      return formatCompact(value);
    case "usd":
      return formatUsd(value);
    case "percent":
      return formatPercent(value);
    case "duration":
      return formatDurationMs(value);
    case "hours":
      return formatHours(value);
    case "count":
      return formatInt(value);
    case "ratio":
      return value.toFixed(1);
  }
}

export type DeltaTone = "up" | "down" | "flat";

export function deltaTone(
  change: number | null,
  goodDirection: GoodDirection,
): { tone: DeltaTone; good: boolean | null } {
  if (change === null || !Number.isFinite(change) || change === 0)
    return { tone: "flat", good: null };
  const tone: DeltaTone = change > 0 ? "up" : "down";
  // A neutral metric keeps its arrow but gets no better/worse verdict.
  if (goodDirection === "neutral") return { tone, good: null };
  return { tone, good: tone === goodDirection };
}

export function metricOf(summary: SummaryResult | undefined, key: MetricKey): Metric | null {
  return summary ? summary.metrics[key] : null;
}
